package de.fellmann.common;

import java.util.HashMap;
import java.util.Map;

public class CountryCodes {
	private Map<String, String> codes = new HashMap<String, String>();
	private static CountryCodes INSTANCE;
	
	public static CountryCodes getInstance() {
		if(INSTANCE == null) {
			INSTANCE = new CountryCodes();
		}
		return INSTANCE;
	}
	
	private CountryCodes() {
		codes.put("AFG", "Afghanistan");
		codes.put("ALB", "Albania");
		codes.put("ALG", "Algeria");
		codes.put("AND", "Andorra");
		codes.put("ANG", "Angola");
		codes.put("ANT", "Antigua and Barbuda");
		codes.put("ARG", "Argentina");
		codes.put("ARM", "Armenia");
		codes.put("ARU", "Aruba");
		codes.put("ASA", "American Samoa");
		codes.put("AUS", "Australia");
		codes.put("AUT", "Austria");
		codes.put("AZE", "Azerbaijan");
		codes.put("BAH", "Bahamas");
		codes.put("BAN", "Bangladesh");
		codes.put("BAR", "Barbados");
		codes.put("BDI", "Burundi");
		codes.put("BEL", "Belgium");
		codes.put("BEN", "Benin");
		codes.put("BER", "Bermuda");
		codes.put("BHU", "Bhutan");
		codes.put("BIH", "Bosnia and Herzegovina");
		codes.put("BIZ", "Belize");
		codes.put("BLR", "Belarus");
		codes.put("BOL", "Bolivia");
		codes.put("BOT", "Botswana");
		codes.put("BRA", "Brazil");
		codes.put("BRN", "Bahrain");
		codes.put("BRU", "Brunei");
		codes.put("BUL", "Bulgaria");
		codes.put("BUR", "Burkina Faso");
		codes.put("CAF", "Central African Republic");
		codes.put("CAM", "Cambodia");
		codes.put("CAN", "Canada");
		codes.put("CAY", "Cayman Islands");
		codes.put("CGO", "Congo");
		codes.put("CHA", "Chad");
		codes.put("CHI", "Chile");
		codes.put("CHN", "China");
		codes.put("CIV", "Côte d'Ivoire");
		codes.put("CMR", "Cameroon");
		codes.put("COD", "DR Congo");
		codes.put("COK", "Cook Islands");
		codes.put("COL", "Colombia");
		codes.put("COM", "Comoros");
		codes.put("CPV", "Cape Verde");
		codes.put("CRC", "Costa Rica");
		codes.put("CRO", "Croatia");
		codes.put("CUB", "Cuba");
		codes.put("CYP", "Cyprus");
		codes.put("CZE", "Czech Republic");
		codes.put("DEN", "Denmark");
		codes.put("DJI", "Djibouti");
		codes.put("DMA", "Dominica");
		codes.put("DOM", "Dominican Republic");
		codes.put("ECU", "Ecuador");
		codes.put("ENG", "England");
		codes.put("EGY", "Egypt");
		codes.put("ERI", "Eritrea");
		codes.put("ESA", "El Salvador");
		codes.put("ESP", "Spain");
		codes.put("EST", "Estonia");
		codes.put("ETH", "Ethiopia");
		codes.put("FIJ", "Fiji");
		codes.put("FIN", "Finland");
		codes.put("FRA", "France");
		codes.put("FSM", "Micronesia");
		codes.put("GAB", "Gabon");
		codes.put("GAM", "Gambia");
		codes.put("GBR", "Great Britain");
		codes.put("GBS", "Guinea-Bissau");
		codes.put("GEO", "Georgia");
		codes.put("GEQ", "Equatorial Guinea");
		codes.put("GER", "Germany");
		codes.put("GHA", "Ghana");
		codes.put("GRE", "Greece");
		codes.put("GRN", "Grenada");
		codes.put("GUA", "Guatemala");
		codes.put("GUI", "Guinea");
		codes.put("GUM", "Guam");
		codes.put("GUY", "Guyana");
		codes.put("HAI", "Haiti");
		codes.put("HKG", "Hong Kong");
		codes.put("HON", "Honduras");
		codes.put("HUN", "Hungary");
		codes.put("INA", "Indonesia");
		codes.put("IND", "India");
		codes.put("IRI", "Iran");
		codes.put("IRL", "Ireland");
		codes.put("IRQ", "Iraq");
		codes.put("ISL", "Iceland");
		codes.put("ISR", "Israel");
		codes.put("ISV", "Virgin Islands");
		codes.put("ITA", "Italy");
		codes.put("IVB", "British Virgin Islands");
		codes.put("JAM", "Jamaica");
		codes.put("JOR", "Jordan");
		codes.put("JPN", "Japan");
		codes.put("KAZ", "Kazakhstan");
		codes.put("KEN", "Kenya");
		codes.put("KGZ", "Kyrgyzstan");
		codes.put("KIR", "Kiribati");
		codes.put("KOR", "South Korea");
		codes.put("KSA", "Saudi Arabia");
		codes.put("KUW", "Kuwait");
		codes.put("LAO", "Laos");
		codes.put("LAT", "Latvia");
		codes.put("LBA", "Libya");
		codes.put("LBR", "Liberia");
		codes.put("LCA", "Saint Lucia");
		codes.put("LES", "Lesotho");
		codes.put("LIB", "Lebanon");
		codes.put("LIE", "Liechtenstein");
		codes.put("LTU", "Lithuania");
		codes.put("LUX", "Luxembourg");
		codes.put("MAD", "Madagascar");
		codes.put("MAR", "Morocco");
		codes.put("MAS", "Malaysia");
		codes.put("MAW", "Malawi");
		codes.put("MDA", "Moldova");
		codes.put("MDV", "Maldives");
		codes.put("MEX", "Mexico");
		codes.put("MGL", "Mongolia");
		codes.put("MHL", "Marshall Islands");
		codes.put("MKD", "Macedonia");
		codes.put("MLI", "Mali");
		codes.put("MLT", "Malta");
		codes.put("MNE", "Montenegro");
		codes.put("MON", "Monaco");
		codes.put("MOZ", "Mozambique");
		codes.put("MRI", "Mauritius");
		codes.put("MTN", "Mauritania");
		codes.put("MYA", "Myanmar");
		codes.put("NAM", "Namibia");
		codes.put("NCA", "Nicaragua");
		codes.put("NED", "Netherlands");
		codes.put("NEP", "Nepal");
		codes.put("NGR", "Nigeria");
		codes.put("NIG", "Niger");
		codes.put("NOR", "Norway");
		codes.put("NRU", "Nauru");
		codes.put("NZL", "New Zealand");
		codes.put("OMA", "Oman");
		codes.put("PAK", "Pakistan");
		codes.put("PAN", "Panama");
		codes.put("PAR", "Paraguay");
		codes.put("PER", "Peru");
		codes.put("PHI", "Philippines");
		codes.put("PLE", "Palestine");
		codes.put("PLW", "Palau");
		codes.put("PNG", "Papua New Guinea");
		codes.put("POL", "Poland");
		codes.put("POR", "Portugal");
		codes.put("PRK", "North Korea");
		codes.put("PUR", "Puerto Rico");
		codes.put("QAT", "Qatar");
		codes.put("ROU", "Romania");
		codes.put("RSA", "South Africa");
		codes.put("RUS", "Russia");
		codes.put("RWA", "Rwanda");
		codes.put("SAM", "Samoa");
		codes.put("SEN", "Senegal");
		codes.put("SEY", "Seychelles");
		codes.put("SIN", "Singapore");
		codes.put("SKN", "Saint Kitts and Nevis");
		codes.put("SLE", "Sierra Leone");
		codes.put("SLO", "Slovenia");
		codes.put("SMR", "San Marino");
		codes.put("SOL", "Solomon Islands");
		codes.put("SOM", "Somalia");
		codes.put("SRB", "Serbia");
		codes.put("SRI", "Sri Lanka");
		codes.put("STP", "São Tomé and Príncipe");
		codes.put("SUD", "Sudan");
		codes.put("SUI", "Switzerland");
		codes.put("SUR", "Suriname");
		codes.put("SVK", "Slovakia");
		codes.put("SWE", "Sweden");
		codes.put("SWZ", "Swaziland");
		codes.put("SYR", "Syria");
		codes.put("TAN", "Tanzania");
		codes.put("TGA", "Tonga");
		codes.put("THA", "Thailand");
		codes.put("TJK", "Tajikistan");
		codes.put("TKM", "Turkmenistan");
		codes.put("TLS", "Timor-Leste");
		codes.put("TOG", "Togo");
		codes.put("TPE", "Chinese Taipei");
		codes.put("TRI", "Trinidad and Tobago");
		codes.put("TUN", "Tunisia");
		codes.put("TUR", "Turkey");
		codes.put("TUV", "Tuvalu");
		codes.put("UAE", "United Arab Emirates");
		codes.put("UGA", "Uganda");
		codes.put("UKR", "Ukraine");
		codes.put("URU", "Uruguay");
		codes.put("USA", "United States");
		codes.put("UZB", "Uzbekistan");
		codes.put("VAN", "Vanuatu");
		codes.put("VEN", "Venezuela");
		codes.put("VIE", "Vietnam");
		codes.put("VIN", "Saint Vincent and the Grenadines");
		codes.put("YEM", "Yemen");
		codes.put("ZAM", "Zambia");
		codes.put("ZIM", "Zimbabwe");
	}

	public String find(String code) {
		return codes.get(code);
	}
	
}
